import React from "react";

const TechSvg = () => {
  return (
    <div>
      <svg
        width="500"
        height="500"
        viewBox="0 0 500 500"
        xmlns="http://www.w3.org/2000/svg"
      >
        <circle
          cx="250"
          cy="250"
          r="200"
          fill="#f3f4f6"
          stroke="#ccc"
          stroke-width="2"
        />

        <circle cx="250" cy="250" r="50" fill="#4a90e2" />
        <rect x="230" y="270" width="40" height="30" fill="#222" rx="5" />

        <text
          x="250"
          y="50"
          font-size="16"
          font-family="Arial"
          text-anchor="middle"
          fill="#333"
        >
          React.js
        </text>
        <text
          x="400"
          y="150"
          font-size="16"
          font-family="Arial"
          text-anchor="middle"
          fill="#333"
        >
          Node.js
        </text>
        <text
          x="450"
          y="300"
          font-size="16"
          font-family="Arial"
          text-anchor="middle"
          fill="#333"
        >
          Laravel
        </text>
        <text
          x="400"
          y="450"
          font-size="16"
          font-family="Arial"
          text-anchor="middle"
          fill="#333"
        >
          Vue.js
        </text>
        <text
          x="250"
          y="470"
          font-size="16"
          font-family="Arial"
          text-anchor="middle"
          fill="#333"
        >
          Next.js
        </text>
        <text
          x="100"
          y="450"
          font-size="16"
          font-family="Arial"
          text-anchor="middle"
          fill="#333"
        >
          Angular
        </text>
        <text
          x="50"
          y="300"
          font-size="16"
          font-family="Arial"
          text-anchor="middle"
          fill="#333"
        >
          Django
        </text>
        <text
          x="100"
          y="150"
          font-size="16"
          font-family="Arial"
          text-anchor="middle"
          fill="#333"
        >
          Express.js
        </text>

        <line
          x1="250"
          y1="250"
          x2="250"
          y2="50"
          stroke="#555"
          stroke-width="2"
        />
        <line
          x1="250"
          y1="250"
          x2="400"
          y2="150"
          stroke="#555"
          stroke-width="2"
        />
        <line
          x1="250"
          y1="250"
          x2="450"
          y2="300"
          stroke="#555"
          stroke-width="2"
        />
        <line
          x1="250"
          y1="250"
          x2="400"
          y2="450"
          stroke="#555"
          stroke-width="2"
        />
        <line
          x1="250"
          y1="250"
          x2="250"
          y2="470"
          stroke="#555"
          stroke-width="2"
        />
        <line
          x1="250"
          y1="250"
          x2="100"
          y2="450"
          stroke="#555"
          stroke-width="2"
        />
        <line
          x1="250"
          y1="250"
          x2="50"
          y2="300"
          stroke="#555"
          stroke-width="2"
        />
        <line
          x1="250"
          y1="250"
          x2="100"
          y2="150"
          stroke="#555"
          stroke-width="2"
        />
      </svg>
    </div>
  );
};

export default TechSvg;
